<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="sampleWebform2.aspx.cs" Inherits="asg5AutoGenerated.sampleWebform2" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
</head>
<body>
    <form id="form1" runat="server">
    <div style="text-align:center;height: 325px";>
        
        <asp:DropDownList ID="ddlCountry" runat="server"></asp:DropDownList>
        <br />
        <asp:Button ID="btnFIlter" runat="server" Text="Button" OnClick="FIlter_Click" />
        
        <asp:GridView ID="gvFilterCusoterInfo" runat="server" HorizontalAlign="Center"></asp:GridView>
         
    </div>
    </form>
</body>
</html>
