using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;
using System.Data;
using System.Configuration;
using System.Data.SqlClient;

namespace asg5AutoGenerated
{
    public partial class sampleWebform2 : System.Web.UI.Page
    {
        string conStr = @"Data Source=DESKTOP-KSO3AP7;Initial Catalog=db_Srinu;Integrated Security=True";
        protected void Page_Load(object sender, EventArgs e)
        {
            if (!IsPostBack)
            {
                SqlConnection Connection = new SqlConnection(conStr);
                Connection.Open();
                string qrCntry = "SELECT DISTINCT(Country) FROM tblCustomer;";
                SqlCommand cmdFilter = new SqlCommand(qrCntry, Connection);
                var result = cmdFilter.ExecuteReader();
                ddlCountry.DataTextField = "Country";
                ddlCountry.DataSource = result;
                ddlCountry.DataBind();
                Connection.Close();
            }
        }

        protected void FIlter_Click(object sender, EventArgs e)
        {
            SqlConnection Connection1 = new SqlConnection(conStr);
            Connection1.Open();
            SqlCommand cd1 = new SqlCommand("getCustomerByCountry", Connection1);
            cd1.CommandType = CommandType.StoredProcedure;
            cd1.CommandText = "getCustomerByCountry";
            cd1.Parameters.Add("Country", SqlDbType.VarChar).Value = ddlCountry.SelectedValue;            
            var ds = cd1.ExecuteReader();
            gvFilterCusoterInfo.DataSource = ds;
            gvFilterCusoterInfo.DataBind();
            Connection1.Close();            
        }
    }
}